service: cake-ordering-system 

provider:
  name: aws
  runtime: nodejs8.10

functions:
  createOrder:
    handler: handler.createOrder
    events:
      - http:
          path: /order
          method: post

resources:
  Resources:
    orderEventsStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: order-events
        ShardCount: 1